bracketSpacing: true
printWidth: 80
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"
plugins:
  - "prettier-plugin-solidity"

overrides:
  - files: "*.sol"
    options:
      compiler: "0.8.25"
      tabWidth: 4
  - files: "*.ts"
