name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  main_ci:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: yarn
      
      - name: Compile
        run: npx hardhat compile
      
      - name: Tests and coverage
        run: npx hardhat coverage
